info:
    app:
        desc: API Bridge To SPASES Service 
        name: bridge-to-spades-modules-bsm
        contact:
           name: Annabi
           email: annabi.mabrouka99@gmail
           website: https://www.mss.tn/
        license: COMMERCIAL
        license-url: 'https://www.mss.tn/LICENSE-1-2'
        version: 1.0.1
       
          
spring:
  application:
    name: AirTravels_Service
  
    
# Security configuration
#  security:
#    user:
#      name: zeddini
#      password: zeddini
  # Database
  datasource: 
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: ':::::::::::: Hikari DS Spades_1-MS POOL ::::::::::::'
      connection-timeout: 60000
      maximum-pool-size: 30
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/MssConsultingAirTravels
    username: postgres
    password: 123
    

  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql : false
    properties:
      hibernate:
        format_sql: true
        
# Logger configuration  
logging:
  pattern:
     console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
     file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  level:
    root: INFO
    org.springframework.web: ERROR
    org.hibernate: ERROR
eureka:
 client:
  fetch-registry: true
  register-with-eureka: true
  service-url:
   default-zone: http://localhost:8761/eurka/
     
server:
  port: 8085